name: 'Scan Files in a Folder'
description: 'Scan all files and output them as a .json file.'
inputs:
  folder:  
    description: 'Folder to scan'
    required: true
    default: './'
  email:  
    description: 'Action email'
    required: false
    default: 'actions@github.com'
  username:  
    description: 'Action username'
    required: false
    default: 'GitHub Actions'
  commit_message:  
    description: 'Commit message'
    required: false
    default: 'Add list of files for selected folder'
  ignored_folders:
    description: 'Ignored folders - the tool will not scan them'
    required: false
  include_ignored_folders:
    description: 'Include ignored folders into the list?'
    required: false
    default: 'false'
runs:
  using: 'node16'
  main: 'dist/index.js'
